[CONSTANTS]
CUBOIDS_COLUMNS = ['label', 'yaw', 'position.x', 'position.y', 'dimensions.x', 'dimensions.y']
PCD_COLUMNS = ['x', 'y', 'z', 'i']
BEV_LABELS = ['Car', 'Bus', 'Pedestrian', 'Bus', 'Pickup Truck']
PCD_AREA_WIDTH = 50
PCD_AREA_HEIGHT = 50
BEV_WIDTH = 640
BEV_HEIGHT = 640
WIDTH_MAGIC = 50
HEIGHT_MAGIC = 50
