[CONSTANTS]
CUBOIDS_COLUMNS = ['label', 'yaw', 'position.x', 'position.y', 'dimensions.x', 'dimensions.y']
PCD_COLUMNS = ['x', 'y', 'z', 'i']
BEV_LABELS = ['Car', 'Bus', 'Pickup Truck', 'Pedestrian']
PCD_AREA_WIDTH = 50
PCD_AREA_HEIGHT = 50
BEV_WIDTH = 640
BEV_HEIGHT = 640
WIDTH_MAGIC = 50
HEIGHT_MAGIC = 50


[PATHS]
PANDASET_PATH = ./training/Pandaset
BEV_DATASET_PATH = ./training/BEV_Dataset
YOLO_DATASET_PATH = ./training/YOLO_data
PCD_PATH = ./training/PCD
PCD_DELETED_PATH = ./training/PCD_DELETED
HD_PATH = ./training/HD


[BEV_SHUFFLE]
NEED_SHUFFLE = True
USE_RANDOM_STATE = True
RANDOM_STATE = 42
# TRAIN + TEST < 100
TRAIN_PERC = 70
TEST_PERC = 15
# VAL = 100 - (TEST + TRAIN)

[YOLO_HYPERPARAMS]
EPOCHS = 150
BATCH = 16
WORKERS = 8